name: Run HomeTest

on:
  workflow_dispatch:

jobs:
  run-home-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run HomeTest class
        run: mvn -Dtest=com.Conference.TestPage.HomeTest test
